### PR TITLE
Add org-mode source

### PR DESCRIPTION
**Pull request by abo-abo**
The whole content is translated to `org-mode`.
It only remains to adapt the css to your liking.
I advice to make the complete switch to `org-mode` if you want to keep
the web-site extensible by others.

### CODE REVIEW

**Comment by picandocodigo** [comment]
This is awesome! Thanks! :smiley: 

I'll review this and check out org-mode exporting to HTML.

**Comment by pank** [comment]
I think it would be great to do the page in Org.  Not only because Org is great to work with, but also, because it's a great example for people who want to do a fancy page based on Org.  

Yet, at the moment the export of Abo's file not quite the same.  I have some changes on my other computer, mostly replacing #+HTML with Org, and changing variable values, that makes it more similar to the current page, but often my CSS knowledge is too limited to get it completely "right".

**Comment by plpxsk** [comment]
I think it's great to add the org-mode source. however, it seems to me that markdown is gaining in popularity compared to org-mode. what are your thoughts on that @abo-abo and others?

**Comment by picandocodigo** [comment]
Right now I think I'd go for keeping it html or going for @pavopax's suggestion to use markdown if I were to change it. What does everyone else think?

**Comment by plpxsk** [comment]
A plus for markdown is that you can combine markdown code and HTML code in one document

Then you can use something like pandoc to generate an HTML only file for the web

**Comment by picandocodigo** [comment]
Closing this as we're staying on HTML for now.

**Pull request closed without merging**
